import {
  Award,
  BookOpen,
  Bot,
  Boxes,
  ClipboardCopy,
  Code,
  FileText,
  FolderGit2,
  GitMerge,
  Globe,
  GraduationCap,
  Image,
  ImagePlus,
  LayoutGrid,
  LayoutTemplate,
  Map,
  MonitorPlay,
  Package,
  Paintbrush,
  Palette,
  Pipette,
  PlayCircle,
  Plug,
  Puzzle,
  Search,
  Server,
  Shapes,
  ScrollText,
  Smartphone,
  Sparkles,
  Swords,
  Type,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "graduation-cap": GraduationCap,
  palette: Palette,
  wrench: Wrench,
  puzzle: Puzzle,
  sparkles: Sparkles,
  "book-open": BookOpen,
  "play-circle": PlayCircle,
  "monitor-play": MonitorPlay,
  award: Award,
  swords: Swords,
  "scroll-text": ScrollText,
  map: Map,
  github: FolderGit2,
  search: Search,
  "layout-grid": LayoutGrid,
  package: Package,
  "clipboard-copy": ClipboardCopy,
  "layout-template": LayoutTemplate,
  shapes: Shapes,
  pipette: Pipette,
  type: Type,
  image: Image,
  paintbrush: Paintbrush,
  server: Server,
  plug: Plug,
  chrome: Globe,
  code: Code,
  bot: Bot,
  "file-text": FileText,
  "image-plus": ImagePlus,
  smartphone: Smartphone,
  "git-merge": GitMerge,
};

export function CategoryIcon({
  name,
  className,
}: {
  name?: string;
  className?: string;
}) {
  const Icon = (name && MAP[name]) || Boxes;
  return <Icon className={className} />;
}
